# [Info]
site_name: 沈超凡的个人网站 # 左上角标题
site_url: https://shen-chaofan.github.io
site_author: 沈超凡
site_description: 沈超凡的个人网站

# [Navigtion]
nav:
  - 讲稿:
    - Lecture/index.md
    - 机器学习和深度学习:
      - 第一课: Lecture/ml&dl/index.md
    - 计算机自然语言处理:
      - 第一课: Lecture/nlp/index.md
    - 计算机视觉与图像处理技术:
      - 第一课: Lecture/cv/index.md
    - 社团&讲座: 
      - 科技前沿分享会: Lecture/lecture/index.md
      - 科研流程分享: Lecture/lecture/how-research.md
      - 文化布局宣讲: Lecture/lecture/cultural-layout.md
      - 科技创新讲座: Lecture/App/index.md
      - 金点子答辩: Lecture/lecture/index.md
  - 博客:
    - Blog/index.md
    - Blog/others.md
    - 复习笔记:
      - Blog/note/nlp.md
    - CG:
      - Blog/ComputerGraphics/cg-notes.md
      - Blog/ComputerGraphics/games101.md
      - Blog/ComputerGraphics/blender-notes.md
    - 游戏:
      - Blog/Game/unity-notes.md
      - Blog/Game/ue-notes.md
      - Blog/Game/what-is-game.md
      - Blog/Game/2d-vs-3d.md
      - Blog/Game/test.md
    - 日语:
      - Blog/Japanese/notes-2202-2203.md
      - Blog/Japanese/notes-2204.md
      - Blog/Japanese/notes-2205.md
      - Blog/Japanese/verb.md
      - Blog/Japanese/adj.md
      - Blog/Japanese/noun.md
      - Blog/Japanese/grammar.md
      - Blog/Japanese/essays.md
      - Blog/Japanese/tantanmen-translation.md
      - Blog/Japanese/chinese.md
    - OS:
      - Blog/OS/fork-exec-spawn.md
      - Blog/OS/fork-example.md
    - Linux:
      - Blog/Linux/vim.md
      - Blog/Linux/tmux.md
      - Blog/Linux/unix.md
      - Blog/Linux/kernel-compile.md
      - Blog/Linux/pi-start.md
    - macOS:
      - Blog/macOS/tree.md
      - Blog/macOS/zoom.md
      - Blog/macOS/sharing-mac-android.md
      - Blog/macOS/mad.md
      - Blog/macOS/stream.md
    - 显示器:
      - Blog//Display/sony-extend.md
    - Apple:
      - Blog/Apple/ipad-recommend.md
      - Blog/Apple/mac-recommend.md
    - GitHub:
      - Blog/GitHub/mirror.md
    - Markdown:
      - Blog/Markdown/grammars.md
      - Blog/Markdown/mkdocs-site.md
      - Blog/Markdown/mdbook-site.md
      - Blog/Markdown/github-pages.md
    - 电子工程:
      - Blog/ElectronicEngineering/verilog-simulation.md
      - Blog/ElectronicEngineering/storage.md
      - Blog/ElectronicEngineering/rlc.md
      - Blog/ElectronicEngineering/yosys-try.md
    - 基础:
      - 数学:
        - Blog/Foundation/Math/latex.md
        - Blog/Foundation/Math/linear.md
        - Blog/Foundation/Math/taylor.md
        - Blog/Foundation/Math/max-pr.md
        - Blog/Foundation/Math/sympy-det.md
      - 物理:
        - Blog/Foundation/Physics/guass-stokes.md
        - Blog/Foundation/Physics/electromagnetics.md
      - 网络:
        - Blog/Network/learning.md
        - Blog/Network/nouns.md
      - 机器学习:
        - Blog/Deeplearning/d2l.md
        - Blog/Deeplearning/speech-recognition.md
        - Blog/Deeplearning/parallel-load.md
        - DDP:
          - Blog/Deeplearning/ddp.md
          - Blog/Deeplearning/ddp-note.md
    - 其他:
      - Blog/Others/video-info.md
  - AI:
    - AI/index.md
    - App:
      - AI/App/flutter-web-consideration.md
    - Flutter:
      - AI/Flutter/commands.md
      - AI/Flutter/dart-lint.md
      - AI/Flutter/template.md
      - AI/Flutter/state-management.md
    - React:
      - AI/React/notes.md
    - 编程:
      - AI/Programming/recommendation.md
      - AI/Programming/my-feelings.md
      - Python:
        - AI/Programming/Python/copy.md
        - AI/Programming/Python/numpy-overview.md
      - Dart:
        - AI/Programming/Dart/learning.md
      - Swift:
        - AI/Programming/Swift/learning-resources.md
        - AI/Programming/Swift/notes-basic-grammars.md
        - AI/Programming/Swift/notes-language-guide.md
        - AI/Programming/Swift/notes-useful-foundation.md
        - AI/Programming/Swift/Lecture-homework.md
        - AI/Programming/Swift/parallel-for.md
      - C:
        - AI/Programming/C/review.md
        - AI/Programming/C/final.md
        - AI/Programming/C/stdout-fflush.md
        - AI/Programming/C/watch-matrix.md
  - 数学:
    - Math/index.md
    - 随笔记:
      - Math/Jottings/2305.md
      - Math/Jottings/2304.md
      - Math/Jottings/2303.md
      - Math/Jottings/2302.md
      - Math/Jottings/2301.md
      - Math/Jottings/2211-2212.md
      - Math/Jottings/2209-2210.md
      - Math/Jottings/2207-2208.md
      - Math/Jottings/2205-2206.md
      - Math/Jottings/2203-2204.md
      - Math/Jottings/2201-2202.md
      - Math/Jottings/2111-2112.md
      - Math/Jottings/2109-2110.md
      - Math/Jottings/2107-2108.md
      - Math/Jottings/2105-2106.md
      - Math/Jottings/2103-2104.md
      - Math/Jottings/2101-2102.md
      - Math/Jottings/2011-2012.md
      - Math/Jottings/2009-2010.md
      - Math/Jottings/2007-2008.md
      - Math/Jottings/2005-2006.md
      - Math/Jottings/2003-2004.md
      - Math/Jottings/2001-2002.md
      - Math/Jottings/0.md
      - Math/Jottings/1906-1912.md
      - Math/Jottings/1807-1812.md
      - Math/Jottings/1801-1806.md
      - Math/Jottings/17.md
      - Math/Jottings/16.md
    - 文章:
      - Math/Articles/230403-buy-phone.md
      - Math/Articles/230305-cccc-memory.md
      - Math/Articles/221227-expressvpn-refund.md
      - Math/Articles/220921-upgrade-introduction.md
      - Math/Articles/220715-macbook-story.md
      - Math/Articles/220624-gratitude.md
      - Math/Articles/220621-bytedance-interview.md
      - Math/Articles/220612-reply.md
      - Math/Articles/2205-good-games.md
      - Math/Articles/220506-stop-jianshu.md
      - Math/Articles/220505-library-thu.md
      - Math/Articles/220415-interestx2.md
      - Math/Articles/220410-job-discussion.md
      - Math/Articles/220410-independence.md
      - Math/Articles/220408-appreciating-girl.md
      - Math/Articles/220402-languages-comparision.md
      - Math/Articles/220324-thoughts-996.md
      - Math/Articles/220107-want-to-be.md
      - Math/Articles/211104-emotion-bad.md
      - Math/Articles/210928-apple-recruitment-share.md
      - Math/Articles/2109-covid-influence.md
      - Math/Articles/2109-group-clear.md
      - Math/Articles/210820-cccc-event.md
      - Math/Articles/210801-affection-3.md
      - Math/Articles/210519-app-AI-experience.md
      - Math/Articles/210516-apple-education-address.md
      - Math/Articles/210502-extend-your-way.md
      - Math/Articles/201119-a-new-review.md
      - Math/Articles/200916-my-pursue.md
      - Math/Articles/200713-sutuo-and-Myself.md
      - Math/Articles/200703-talk-with-junior.md
      - Math/Articles/200607-gaokao-memory.md
      - Math/Articles/200604-small-goal.md
      - Math/Articles/200602-tennkinoko.md
      - Math/Articles/200506-why.md
      - Math/Articles/2005-travel.md
      - Math/Articles/190730-tangyan-rd-23.md
      - Math/Articles/190723-feelings-in-6-days.md
      - Math/Articles/190707-address-to-nonlocal-students.md
      - Math/Articles/190629-affection-2.md
      - Math/Articles/1905-non-intelligent.md
      - Math/Articles/1901-go-to-thu.md
      - Math/Articles/1811-do-it.md
      - Math/Articles/1808-ideality-and-reality.md
      - Math/Articles/1806-apply-thu.md
      - Math/Articles/18-tree.md
      - Math/Articles/18-what-i-love.md
      - Math/Articles/17-dream-2017.md
      - Math/Articles/14-affection-1.md
    - 随笔:
      - Math/Literature/proses.md
      - Math/Literature/poems.md
  - 技术栈:

  - 转载:
    - Reproduce/index.md
    - Reproduce/how-to-ask-questions-the-smart-way.md
    - Reproduce/tim-cook-at-duke.md
    - Reproduce/my-best-teacher.md
    - Reproduce/kasi/watagumo.md
  - 我:
    - Myself/index.md
    - Myself/cv-full.md
    - Myself/suki.md
    - Myself/create-family.md
    - Myself/support.md
  - 网站:
    - WEBSITE/index.md # 访客打开网站第一个看到的是 docs/index.md（会报错 The following pages exist in the docs directory, but are not included in the "nav" configuration: index.md 不要紧）  如果访客之后想要重新看到这个界面  可以在 docs/WEBSITE/index.md 找到
    - WEBSITE/build.md
    - WEBSITE/help.md
    - WEBSITE/test.md

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 可以通过按钮复制代码
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/jarrycf/jarrycf.github.io/actions # 右上角点击跳转的链接
repo_name: jarrycf.github.io # 右上角的名字
## [bottom-left corner]
copyright: 沈超凡 CC-BY-4.0 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1352921332
      name: Bilibili | 镜像tru # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/jarrycf
      name: GitHub | jarrycf

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/Blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要

extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
